# Generated by Django 6.0.7 on 2026-08-04 00:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('weekdays', models.JSONField(default=list, verbose_name='dias da semana')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='horário planejado')),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='estimativa em minutos')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=6, verbose_name='prioridade')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='início')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_items', to='categories.category', verbose_name='categoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_items', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'item de rotina semanal',
                'verbose_name_plural': 'itens de rotina semanal',
                'ordering': ('is_active', 'scheduled_time', 'title', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RoutineOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('occurrence_date', models.DateField(verbose_name='data da ocorrência')),
                ('scheduled_time_snapshot', models.TimeField(blank=True, null=True, verbose_name='horário preservado')),
                ('title_snapshot', models.CharField(max_length=180, verbose_name='título preservado')),
                ('category_snapshot', models.CharField(blank=True, default='', max_length=80, verbose_name='categoria preservada')),
                ('category_color_token_snapshot', models.CharField(blank=True, default='', max_length=32, verbose_name='cor da categoria preservada')),
                ('estimated_minutes_snapshot', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='estimativa preservada em minutos')),
                ('priority_snapshot', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], max_length=6, verbose_name='prioridade preservada')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('skipped', 'Pulada')], default='pending', max_length=9, verbose_name='status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('skipped_at', models.DateTimeField(blank=True, null=True, verbose_name='pulada em')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.workspace', verbose_name='workspace')),
                ('routine_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='routines.weeklyroutineitem', verbose_name='item de rotina')),
            ],
            options={
                'verbose_name': 'ocorrência de rotina',
                'verbose_name_plural': 'ocorrências de rotina',
                'ordering': ('occurrence_date', 'scheduled_time_snapshot', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='weeklyroutineitem',
            index=models.Index(fields=['workspace', 'is_active', 'starts_on'], name='routine_item_scope_active_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyroutineitem',
            index=models.Index(fields=['workspace', 'starts_on', 'ends_on'], name='routine_item_scope_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklyroutineitem',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ('low', 'medium', 'high'))), name='routine_item_valid_priority'),
        ),
        migrations.AddConstraint(
            model_name='weeklyroutineitem',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_minutes__isnull', True), ('estimated_minutes__gte', 1), _connector='OR'), name='routine_item_positive_est'),
        ),
        migrations.AddConstraint(
            model_name='weeklyroutineitem',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='routine_item_valid_dates'),
        ),
        migrations.AddIndex(
            model_name='routineoccurrence',
            index=models.Index(fields=['workspace', 'occurrence_date', 'status'], name='routine_occ_scope_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='routineoccurrence',
            constraint=models.UniqueConstraint(fields=('routine_item', 'occurrence_date'), name='unique_routine_item_date'),
        ),
        migrations.AddConstraint(
            model_name='routineoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'completed', 'skipped'))), name='routine_occ_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='routineoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('priority_snapshot__in', ('low', 'medium', 'high'))), name='routine_occ_valid_priority'),
        ),
        migrations.AddConstraint(
            model_name='routineoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_minutes_snapshot__isnull', True), ('estimated_minutes_snapshot__gte', 1), _connector='OR'), name='routine_occ_positive_est'),
        ),
    ]
