# Generated by Django 6.0.7 on 2026-07-31 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'workspace',
                'verbose_name_plural': 'workspaces',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=10, verbose_name='papel')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'membership de workspace',
                'verbose_name_plural': 'memberships de workspace',
                'ordering': ('workspace_id', 'user_id'),
                'indexes': [models.Index(fields=['workspace', 'user', 'is_active'], name='workspace_member_scope_idx'), models.Index(fields=['user', 'is_active'], name='workspace_member_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_membership_user'), models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'member'])), name='workspace_membership_valid_role')],
            },
        ),
    ]
