# Generated by Django 6.0.7 on 2026-07-31

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_settings_for_existing_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    UserSettings = apps.get_model('accounts', 'UserSettings')

    UserSettings.objects.bulk_create(
        [UserSettings(user_id=user.pk) for user in User.objects.only('pk')]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='criado em',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='atualizado em',
                    ),
                ),
                (
                    'theme',
                    models.CharField(
                        choices=[
                            ('system', 'Sistema'),
                            ('light', 'Claro'),
                            ('dark', 'Escuro'),
                        ],
                        default='system',
                        max_length=10,
                        verbose_name='tema',
                    ),
                ),
                (
                    'timezone',
                    models.CharField(
                        default='America/Sao_Paulo',
                        max_length=64,
                        validators=[accounts.models.validate_timezone],
                        verbose_name='fuso horário',
                    ),
                ),
                (
                    'language',
                    models.CharField(
                        choices=[('pt-br', 'Português (Brasil)')],
                        default='pt-br',
                        max_length=10,
                        verbose_name='idioma',
                    ),
                ),
                (
                    'date_format',
                    models.CharField(
                        choices=[
                            ('DD/MM/YYYY', 'DD/MM/AAAA'),
                            ('DD/MM/YY', 'DD/MM/AA'),
                            ('YYYY-MM-DD', 'AAAA-MM-DD'),
                        ],
                        default='DD/MM/YYYY',
                        max_length=12,
                        verbose_name='formato de data',
                    ),
                ),
                (
                    'time_format',
                    models.CharField(
                        choices=[
                            ('24h', '24 horas (14:30)'),
                            ('12h', '12 horas (2:30 PM)'),
                        ],
                        default='24h',
                        max_length=4,
                        verbose_name='formato de horário',
                    ),
                ),
                (
                    'default_focus_minutes',
                    models.PositiveSmallIntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name='duração padrão do foco',
                    ),
                ),
                (
                    'default_break_minutes',
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name='duração padrão da pausa',
                    ),
                ),
                (
                    'focus_end_sound_enabled',
                    models.BooleanField(
                        default=True,
                        verbose_name='som ao encerrar o foco',
                    ),
                ),
                (
                    'onboarding_completed',
                    models.BooleanField(
                        default=False,
                        verbose_name='onboarding concluído',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='settings',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='usuário',
                    ),
                ),
            ],
            options={
                'verbose_name': 'configuração do usuário',
                'verbose_name_plural': 'configurações dos usuários',
                'ordering': ('user_id',),
            },
        ),
        migrations.RunPython(
            create_settings_for_existing_users,
            migrations.RunPython.noop,
        ),
    ]
