# Generated by Django 6.0.7 on 2026-07-31

import django.db.models.deletion
from django.db import migrations, models
from django.db.models.functions import Lower


DEFAULT_CATEGORIES = (
    ('Estudos', 'estudos', 'brand-600'),
    ('Trabalho', 'trabalho', 'cyan-200'),
    ('Pessoal', 'pessoal', 'success-600'),
    ('Saúde', 'saude', 'danger-600'),
)


def create_initial_categories(apps, schema_editor):
    Workspace = apps.get_model('tenants', 'Workspace')
    Category = apps.get_model('categories', 'Category')

    for workspace in Workspace.objects.only('pk').iterator():
        for name, slug, color_token in DEFAULT_CATEGORIES:
            Category.objects.get_or_create(
                workspace_id=workspace.pk,
                slug=slug,
                defaults={
                    'name': name,
                    'color_token': color_token,
                    'is_system': True,
                },
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='criado em',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='atualizado em',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=80, verbose_name='nome'),
                ),
                (
                    'slug',
                    models.SlugField(
                        allow_unicode=True,
                        max_length=80,
                        verbose_name='slug',
                    ),
                ),
                (
                    'color_token',
                    models.CharField(
                        choices=[
                            ('brand-600', 'Azul principal'),
                            ('cyan-200', 'Ciano'),
                            ('success-600', 'Verde'),
                            ('warning-600', 'Âmbar'),
                            ('danger-600', 'Vermelho'),
                        ],
                        default='brand-600',
                        max_length=32,
                        verbose_name='token de cor',
                    ),
                ),
                (
                    'icon_key',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=40,
                        verbose_name='ícone',
                    ),
                ),
                (
                    'is_system',
                    models.BooleanField(
                        default=False,
                        verbose_name='padrão do sistema',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='ativa'),
                ),
                (
                    'workspace',
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='tenants.workspace',
                        verbose_name='workspace',
                    ),
                ),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('name', 'pk'),
                'indexes': [
                    models.Index(
                        fields=['workspace', 'is_active', 'name'],
                        name='category_workspace_active_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('workspace', 'slug'),
                        name='unique_workspace_category_slug',
                    ),
                    models.UniqueConstraint(
                        Lower('name'),
                        'workspace',
                        name='unique_workspace_category_name_ci',
                    ),
                ],
            },
        ),
        migrations.RunPython(
            create_initial_categories,
            migrations.RunPython.noop,
        ),
    ]
