# Generated by Django 6.0.7 on 2026-08-01 21:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=6, verbose_name='prioridade')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='data planejada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída')], default='pending', max_length=9, verbose_name='status')),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='estimativa em minutos')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('onboarding', 'Onboarding'), ('ai', 'IA')], default='manual', max_length=10, verbose_name='origem')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='categories.category', verbose_name='categoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'status', 'due_date'], name='task_workspace_status_due_idx'), models.Index(fields=['workspace', 'completed_at'], name='task_workspace_completed_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'completed'))), name='task_valid_status'), models.CheckConstraint(condition=models.Q(('priority__in', ('low', 'medium', 'high'))), name='task_valid_priority'), models.CheckConstraint(condition=models.Q(('source__in', ('manual', 'onboarding', 'ai'))), name='task_valid_source'), models.CheckConstraint(condition=models.Q(('estimated_minutes__isnull', True), ('estimated_minutes__gte', 1), _connector='OR'), name='task_positive_estimate')],
            },
        ),
    ]
