# Generated by Django 5.2.4 on 2026-08-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='board_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordem no quadro'),
        ),
    ]
