# Generated by Django 6.0.7 on 2026-07-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='criado em',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='atualizado em',
                    ),
                ),
                (
                    'current_step',
                    models.CharField(
                        choices=[
                            ('name', 'Nome'),
                            ('areas', 'Áreas'),
                            ('focus', 'Foco padrão'),
                            ('task', 'Primeira tarefa'),
                            ('routine', 'Rotina'),
                            ('complete', 'Concluído'),
                        ],
                        default='name',
                        max_length=16,
                        verbose_name='etapa atual',
                    ),
                ),
                (
                    'completed_steps',
                    models.JSONField(
                        default=list,
                        verbose_name='etapas concluídas',
                    ),
                ),
                (
                    'data',
                    models.JSONField(
                        default=dict,
                        verbose_name='dados do onboarding',
                    ),
                ),
                (
                    'is_skipped',
                    models.BooleanField(default=False, verbose_name='foi pulado'),
                ),
                (
                    'completed_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='concluído em',
                    ),
                ),
                (
                    'skipped_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='pulado em',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='onboarding_progress',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='usuário',
                    ),
                ),
            ],
            options={
                'verbose_name': 'progresso do onboarding',
                'verbose_name_plural': 'progressos do onboarding',
                'ordering': ('user_id',),
            },
        ),
    ]
